# Generated by Django 2.2 on 2020-10-20 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='hobby_picture',
            field=models.CharField(default='https://icebreakerideas.com/wp-content/uploads/2018/07/57-Best-List-of-Hobbies-For-Men-and-Women.jpeg', max_length=500),
        ),
    ]
